#pragma once

namespace vitamaps {

enum class UiText {
    TextEntry,
    TextTooLong,
    TextConfirm,
    KeyboardError,
    PinModeInstruction,
    ListFull,
    PointSaved,
    RamOnly,
    SearchBusy,
    SearchPrompt,
    CoordinatesFound,
    LocalFound,
    SearchStartFailed,
    SearchRunning,
    SearchNotFound,
    SearchOffline,
    SearchFailed,
    SearchCached,
    SearchFound,
    NewList,
    ListCreated,
    ListCreateFailed,
    RenameList,
    ListRenamed,
    OnlyListCannotDelete,
    ConfirmDeleteList,
    ListDeleted,
    PointCentered,
    RenamePoint,
    PointRenamed,
    ConfirmDeletePoint,
    PointDeleted,
    PinModeEnded,
    CenterStatus,
    Online,
    Offline,
    Save,
    Pin,
    Finish,
    Lists,
    Search,
    Options,
    Zoom,
    PinSummary,
    ListsAndRoutes,
    PinCount,
    ActiveSuffix,
    Open,
    New,
    Rename,
    Delete,
    Map,
    StopsDistance,
    StopsDistanceArea,
    RoutingUnavailable,
    EmptyList,
    Center,
    Reorder,
    SettingsTitle,
    MapStyle,
    Language,
    HudBehavior,
    Crosshair,
    Units,
    Animations,
    PersistentLogs,
    HudAuto,
    AlwaysVisible,
    Visible,
    Hidden,
    Imperial,
    Metric,
    Reduced,
    Smooth,
    Enabled,
    Disabled,
    Saved,
    Error,
    SelectChange,
    Change,
    Back,
    Quit,
    DefaultFavorites,
    DefaultPoint,
    CacheMaps,
    CacheReading,
    CacheState,
    CacheConfirm,
    CacheClearing,
    CacheCleared,
    CacheClearFailed,
    Clear,
    ShowHide,
    ClosePath,
    OpenPath,
    Closed,
    NeedThreePoints,
    StartPoint,
    North,
    Rotate,
    Count,
};

// 0 = console language, followed by the explicitly selectable languages.
constexpr int kUiLanguageSettingCount = 12;

void ui_localization_init(int language_setting);
int ui_language_setting();
const char *ui_text(UiText text);
const char *ui_language_name(int language_setting);
const char *ui_language_http_tag();
unsigned int ui_language_ime_mask();

} // namespace vitamaps
