#!/usr/bin/env python3
"""Generate VitaMaps' compact populated-place table from Natural Earth."""

import argparse
import json
import math
from pathlib import Path


ITALIAN_NAMES = {
    "Florence": "Firenze",
    "Genoa": "Genova",
    "Milan": "Milano",
    "Naples": "Napoli",
    "Rome": "Roma",
    "Turin": "Torino",
    "Venice": "Venezia",
}


def world_point(longitude: float, latitude: float) -> tuple[float, float]:
    latitude = max(-85.0511287798066, min(85.0511287798066, latitude))
    radians = math.radians(latitude)
    x = ((longitude + 180.0) / 360.0) % 1.0
    y = (1.0 - math.log(math.tan(radians) + 1.0 / math.cos(radians)) /
         math.pi) * 0.5
    return x, max(0.0, min(1.0, y))


def cpp_string(value: str) -> str:
    # JSON strings use the same escaping required by these UTF-8 C++ literals.
    return json.dumps(value, ensure_ascii=False)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    document = json.loads(args.input.read_text(encoding="utf-8"))
    places = []
    for feature in document["features"]:
        properties = feature["properties"]
        coordinates = feature["geometry"]["coordinates"]
        name = properties.get("name") or properties.get("nameascii")
        if not name or len(coordinates) < 2:
            continue
        if properties.get("adm0name") == "Italy":
            name = ITALIAN_NAMES.get(name, name)
        longitude = float(coordinates[0])
        latitude = float(coordinates[1])
        x, y = world_point(longitude, latitude)
        minimum_zoom = int(round(float(properties.get("min_zoom") or 9.0) * 10.0))
        label_rank = max(1, min(255, int(properties.get("labelrank") or 9)))
        population = max(0, min(0xFFFFFFFF, int(properties.get("pop_max") or 0)))
        places.append((label_rank, -population, minimum_zoom, name,
                       x, y, population))

    # Runtime traversal is therefore already importance ordered and needs no
    # heap allocation or sort on the Vita render thread.
    places.sort()
    lines = [
        "// Generated by tools/generate-place-labels.py from Natural Earth",
        "// ne_10m_populated_places_simple (public domain). Do not edit.",
    ]
    for rank, _, minimum_zoom, name, x, y, population in places:
        lines.append(
            f"    {{{cpp_string(name)}, {x:.9f}F, {y:.9f}F, "
            f"{population}U, {minimum_zoom}U, {rank}U}},")
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"generated {len(places)} place labels -> {args.output}")


if __name__ == "__main__":
    main()
